
WITH numberedSupplier AS(
    SELECT 
        *,
        ROW_NUMBER()OVER (
            PARTITION BY supplier_id
            ORDER BY supplier_id
        ) AS rn
    FROM {{source('raw','supplier_raw')}}
)
SELECT 
    SUPPLIER_ID, 
    SUPPLIER_NAME,
    SUPPLIER_TYPE,
    TAX_ID,
    WEBSITE,
    CREDIT_RATING,
    PAYMENT_TERMS,
    PREFERRED_CARRIER,
    IS_ACTIVE,
    YEAR_ESTABLISHED,
    LEAD_TIME_DAYS,
    MINIMUM_ORDER_QUANTITY,
    LAST_ORDER_DATE,
    LAST_MODIFIED_DATE,
    CONTACT_PERSON,
    CONTACT_EMAIL,
    CONTACT_PHONE,
    CONTACT_ADDRESS,
    CONTRACT_ID,
    CONTRACT_START_DATE,
    CONTRACT_END_DATE,
    CONTRACT_RENEWAL_OPTION,
    CONTRACT_EXCLUSIVITY,
    AVERAGE_DELAY_DAYS,
    DEFECT_RATE,
    ON_TIME_DELIVERY_RATE,
    RETURNS_PERCENTAGE,
    RESPONSE_TIME_HOURS,
    QUALITY_RATING,
    CATEGORIES_SUPPLIED,
    RECORD_HASH,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT,
    LOAD_TIMESTAMP,
    FILENAME,
    FILE_ROW_NUMBER
FROM
    NumberedSupplier
WHERE
    rn = 1
